import { createProviderToolFactoryWithOutputSchema } from "@ai-sdk/provider-utils"
import { Schema } from "effect"

// The Responses API names the code interpreter container with this id.
export const ContainerID = Schema.String.pipe(Schema.brand("CopilotResponses.ContainerID"))

export const codeInterpreterInputSchema = Schema.Struct({
  code: Schema.optional(Schema.NullOr(Schema.String)),
  containerId: ContainerID,
}).annotate({ identifier: "CopilotResponses.CodeInterpreterInput" })

export const codeInterpreterOutputSchema = Schema.Struct({
  outputs: Schema.optional(
    Schema.NullOr(
      Schema.mutable(
        Schema.Array(
          Schema.Union([
            Schema.Struct({ type: Schema.Literal("logs"), logs: Schema.String }),
            Schema.Struct({ type: Schema.Literal("image"), url: Schema.String }),
          ]),
        ),
      ),
    ),
  ),
}).annotate({ identifier: "CopilotResponses.CodeInterpreterOutput" })

export const codeInterpreterArgsSchema = Schema.Struct({
  container: Schema.optional(
    Schema.Union([
      Schema.String,
      Schema.Struct({
        fileIds: Schema.optional(Schema.mutable(Schema.Array(Schema.String))),
      }),
    ]),
  ),
}).annotate({ identifier: "CopilotResponses.CodeInterpreterArgs" })

type CodeInterpreterArgs = {
  /**
   * The code interpreter container.
   * Can be a container ID
   * or an object that specifies uploaded file IDs to make available to your code.
   */
  container?: string | { fileIds?: string[] }
}

export const codeInterpreterToolFactory = createProviderToolFactoryWithOutputSchema<
  {
    /**
     * The code to run, or null if not available.
     */
    code?: string | null

    /**
     * The ID of the container used to run the code.
     */
    containerId: string
  },
  {
    /**
     * The outputs generated by the code interpreter, such as logs or images.
     * Can be null if no outputs are available.
     */
    outputs?: Array<
      | {
          type: "logs"

          /**
           * The logs output from the code interpreter.
           */
          logs: string
        }
      | {
          type: "image"

          /**
           * The URL of the image output from the code interpreter.
           */
          url: string
        }
    > | null
  },
  CodeInterpreterArgs
>({
  id: "openai.code_interpreter",
  inputSchema: Schema.toStandardSchemaV1(Schema.toStandardJSONSchemaV1(codeInterpreterInputSchema)),
  outputSchema: Schema.toStandardSchemaV1(Schema.toStandardJSONSchemaV1(codeInterpreterOutputSchema)),
})

export const codeInterpreter = (
  args: CodeInterpreterArgs = {}, // default
) => {
  return codeInterpreterToolFactory(args)
}
