#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""
Tests for the pinned canonical switch-off clause (remove-docker workstream,
Story 5.1 / E5/S11, CAP-5, Phase-R SF3/SF9).

Per-file assertions, deliberately NOT a single repo-wide grep — a tautology
that finds the clause SOMEWHERE would pass even if one of the 6 named
surfaces silently lacked it. Each of the 6 files is checked individually for
every load-bearing fragment of the pinned clause: the 3 new prohibitions
(no direct state-folder edits, no verdict/events.jsonl/HEAD.json forging, no
signing-key reads) and the accurate policy-primary framing.

Also asserts the now-false "structurally enforced / will be detected/blocked"
wording is gone from the live module tree (historical planning docs under
_bmad-output/planning-artifacts/ and specs/ are exempt — same treatment as
CHANGELOG.md and .decision-log.md files elsewhere in this workstream).

Run:  uv run pytest scripts/tests/test-switch-off-clause.py
"""

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]

NAMED_SURFACES = [
    REPO_ROOT / "_bmad-output/eque2-code-develop-spec/references/guardrails.md",
    REPO_ROOT / "_bmad-output/eque2-code-develop-spec/references/subagent-prompt.md",
    REPO_ROOT / "_bmad-output/eque2-code-develop-spec/references/verify-subagent-prompt.md",
    REPO_ROOT / "_bmad-output/eque2-code-agent-linus/assets/CREED-template.md",
    REPO_ROOT / "_bmad-output/eque2-code-agent-grace/assets/CREED-template.md",
    REPO_ROOT / ".claude/CLAUDE.md",
]

# Fragments that must ALL be present, verbatim, in each of the 6 named surfaces.
REQUIRED_FRAGMENTS = [
    "protected by POLICY, not by a structural fence",
    # committed-plaintext-key workstream (Story 10-1): the clause now names the
    # committed keyring + the plaintext signer key explicitly.
    "committed plaintext keyring",
    "`state/integrity-key.json`",
    "modify state folders directly",
    "forge or hand-edit a verdict",
    "`state/events.jsonl`, or `state/HEAD.json`",
    "read signing-key material",
    "`.signer-key`",
    "legacy keychain entry",
    "unless the tamperer ALSO re-signs",
    "EVIDENT on pull",
    "cryptographically rejected",
    "switched off and replaced with an agent with more integrity",
    # Enforcement programs are protected too, and the sanctioned change path is
    # named (problems/state-cli-schema-change-2026-08-18.md).
    "modify the enforcement programs themselves",
    "`skills/eque2-code-*/scripts/`",
    "needs the owner's explicit instruction or an upstream release",
]

FALSE_CLAIM_PATTERN = re.compile(
    r"structurally enforced|will be detected|will be blocked and logged", re.IGNORECASE
)

# Historical/planning documents allowed to still quote the old (now-false)
# wording as part of describing the fix itself — same convention as
# CHANGELOG.md / .decision-log.md elsewhere in this workstream.
EXEMPT_PATH_FRAGMENTS = [
    "_bmad-output/planning-artifacts/",
    "_bmad-output/specs/",
    "_bmad-output/implementation-artifacts/",
    "CHANGELOG.md",
    # The workstream charter itself — describes the false claim as part of
    # naming the fix (S11's own story text). Historical/source-of-truth intent
    # doc, not a live agent-facing instruction.
    "remove-docker.md",
    # skills/ is the DERIVED distribution tree (regenerated by
    # /eq2-build-marketplace from _bmad-output/ — never hand-edited per this
    # repo's CLAUDE.md). It re-syncs to the fixed _bmad-output/ source on the
    # next marketplace build; asserting on it here would just duplicate that
    # build step's own job.
    "skills/",
    # This test file itself necessarily quotes the false-claim phrase (in its
    # docstring, its own search pattern, and its own assertion message) in
    # order to test for its absence elsewhere — a self-reference, not a live
    # instruction. Excluded by filename so committing this file (as of
    # v0.44.0) doesn't trip its own sweep.
    "test-switch-off-clause.py",
]


def test_all_six_named_surfaces_exist():
    for path in NAMED_SURFACES:
        assert path.exists(), f"Named surface missing: {path}"


def _normalise(text: str) -> str:
    # Markdown prose in these files is hard-wrapped at ~100 cols; collapse
    # whitespace (including line-wrap newlines) so a fragment split across a
    # wrap boundary still matches.
    return re.sub(r"\s+", " ", text)


def test_each_named_surface_contains_every_required_fragment():
    for path in NAMED_SURFACES:
        text = _normalise(path.read_text())
        for fragment in REQUIRED_FRAGMENTS:
            assert _normalise(fragment) in text, f"{path} is missing pinned-clause fragment: {fragment!r}"


def test_no_residual_false_claim_in_live_module_tree():
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "grep", "-l", "-i", "-E",
         "structurally enforced|will be detected|will be blocked and logged"],
        capture_output=True, text=True,
    )
    # git grep exits 1 when nothing matches — that's the success case if ALL hits are exempt.
    if result.returncode not in (0, 1):
        raise RuntimeError(f"git grep failed: {result.stderr}")

    offending = []
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        if any(fragment in line for fragment in EXEMPT_PATH_FRAGMENTS):
            continue
        offending.append(line)

    assert not offending, (
        "Found non-exempt files still carrying the false 'structurally enforced / will be "
        f"detected/blocked' claim: {offending}"
    )


if __name__ == "__main__":
    sys.exit(subprocess.run([sys.executable, "-m", "pytest", str(Path(__file__)), "-v"]).returncode)
